### ISSUE TITLE
url not accessible http://www.yourwebsite.com/msp_bancasella/listener/index

### ISSUE THREAD

**Issue by rswstudio** [magespecialist/MSP_Bancasella#1]
Hi,

url http://www.yourwebsite.com/msp_bancasella/listener/index and other are not accessible in domain. Error 404 page not found. There is a configuration in htacces?

**Comment by midimarcus** [comment]
Hello,
usually listeners are not accessible via direct URL, so it's normal you get a 404 error trying to reach such URL, 
You should try if gateway works fine in normal conditions at checkout.
If checkout doesn't run smooth, please, first of all check your domain to be sure you're using right one (not www.yourwebsite.com :) and the double check Gateway settings such as IP address whitelist, return URLs and other website/gateway specific settings.
Then try to give a look to gateway logs both in magento and in Banca Sella's control panel to get some more details about error if any.

**Comment by rswstudio** [comment]
Hi,customer can pay with credit card. Money are in Banca Sella and available. But Banca Sella mail order is not sent.

The error:
La invitiamo quindi a controllare, o a far controllare dalla struttura tecnica che La assiste, gli indirizzi (URL) attualmente inseriti nelle pagine di gestione degli ordini di pagamento (Back Office) di GestPay (https://ecomm.sella.it/gestpay), nella sezione Configurazione, alla voce Risposte, ed in particolare che:
a) l'url ''server to server'' sia raggiungibile e visualizzabile tramite Internet;
b) l'url ''server to server'' sia impostato con l'indirizzo IP senza la configurazione di porte di ingresso ed uscita relative ad un firewall (ad es.: www.aaa.it:9000 o www.aaa.it:8080).

![image](https://cloud.githubusercontent.com/assets/14092515/10076274/f6332532-62da-11e5-9a01-ae1682d0ca9b.png)

**Comment by rswstudio** [comment]
Is possible php version 5.3 or php soap not present or other components?

**Comment by midimarcus** [comment]
Hello,
are you using a domain via custom hosts file visible only from your computer? Or any kind of basic authentication?
In this case BancaSella's servers cannot reach your server. You need a publicly reachable domain.
Please double check.

I doubt php version or soap can interfere in this case.
Thanks.

**Comment by rswstudio** [comment]
of course not. A public accessible url: shop.roces.com

2015-09-24 17:00 GMT+02:00 Marco Giorgetti notifications@github.com:

> Hello,
> are you using a domain via custom hosts file visible only from your
> computer? Or any kind of basic authentication?
> In this case BancaSella's servers cannot reach your server. You need a
> publicly reachable domain.
> Please double check.
> 
> I doubt php version or soap can interfere in this case.
> Thanks.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/magespecialist/MSP_Bancasella/issues/1#issuecomment-142955098
> .

## 

_COMUNICAZIONE DI SERVIZIO *- Causa passaggio utenze telefoniche presso
altro operatore, vi ricordiamo che la *linea telefonica principale di RSW
Studio è la seguente:_ _Tel. 0425 460364_

---

_RSW Studio S.n.c._
Via Umberto I, 31 - 45100 Rovigo
Tel. _0425 460364_ - Fax 0425 1661066
Cell. 328.6412223
Email: info@rswstudio.it - WebSite: www.rswstudio.it
www.facebook.com/RSWStudioWeb

---

INFORMATIVA PRIVACY D.L. 196/03
Le informazioni contenute o allegate alla presente e-mail sono rivolte
unicamente alle persone cui la e-mail è indirizzata, e possono contenere
informazioni la cui riservatezza è tutelata. Sono vietati la riproduzione,
la distruzione, la copie e l'uso di questa e-mail in mancanza di
autorizzazione del destinatario. Se avete ricevuto questa e-mail per
errore, vogliate cortesemente darne notifica al Mittente, tramite fax o
mail. Quanto precede è valido ai fini del rispetto del D.Lgs. 196/03, sulla
tutela dei dati personali

**Comment by midimarcus** [comment]
Ok,
since your site has multiple languages could you please check if you need language code in GestPay urls? Ex: http://shop.roces.com/it/msp_bancasella/listener/index
Hint: turn on magento logs and take a look to web server error log to get some more details about issue.
