### ISSUE TITLE
How can disable auto invoice?

### ISSUE THREAD

**Issue by ghost** [magespecialist/MSP_Bancasella#2]
Hi Marco, my customer needs to disable auto invoicing that it generates 
when proceed to bancasella payment gateway. 
Is it possible?

Auto invoicing doens't allow to set an order on status "complete".
Magento version 1.9.2.0

Thanks in advance.

**Comment by phoenix128** [comment]
Hello plumastudio,
try commenting out MSP_Bancasella_Model_Gateway::processInvoice() method's content.

Just replace the content of that method with a simple "return $this"

**Comment by ghost** [comment]
Nothing. It doesn't works.
It always generates auto invoice. :(

Another suggestion, please?
Thanks in advance.

**Comment by phoenix128** [comment]
The problem is that you should disable the transaction registration, but it may generate some side effect.

You can try changing `MSP_Bancasella_Model_Api::handleListenerMessage` disabling the if at line 172:

`if (false && $transactionUpdate)`

Please test this before putting in production.

**Comment by ghost** [comment]
Nothing. It doesn't works.
i really appreciate your support.

Thanks

**Comment by phoenix128** [comment]
You could try setting "Authorize Only" in the payment action in your MSP_BancaSella Payment Settings. I do not see any other solution, because Magento creates invoices during the "capture" procedure, so the only way I see is to change that value.

Let me know if it works.

**Comment by ghost** [comment]
You right! :)
Now, invoice has't been created automatically. Work like a charm!

Again, thank for your support!
